spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  frontend-url: https://victorious-sky-0bae2b900.1.azurestaticapps.net
